### ISSUE TITLE
Templates shouldn't assume gcc/clang

### ISSUE THREAD

**Issue by delcypher** [mshockwave/generator-llvm#1]
The template contains

```cmake
if(NOT ${LLVM_ENABLE_RTTI})
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti")
  message(STATUS "Disable RTTI")
endif()
```

There are several things that aren't great about this

* This assumes the compiler is gcc/clang
* It assumes the compiler supports the `-fno-rtti` flag.

Really the CMake code should check what the compiler is and then test the appropriate flag to check whether or the not the compiler supports it.

**Comment by mshockwave** [comment]
@delcypher Thanks for replying!
I think your suggestion make sense, I'll fix it
Or you can create a PR as well : )

**Comment by mshockwave** [comment]
Fixed.
For less popular compilers, it wouldn't add any RTTI flag
